### ISSUE TITLE
'not' keyword isn't working as expected

### ISSUE THREAD

**Issue by ttamminen** [jangxyz/expect.underscore.js#2]
`expect([{ name: '1' }, { name: '2' }, { name: '3' }]).not.to._.find('name', '3');`

or

`expect([{ name: '1' }, { name: '2' }, { name: '3' }]).not.to._.find({ 'name': '3' });`

Should fail as name is found and it should not be found.

**Comment by jangxyz** [comment]
Hi. I just fixed the bug. Can you try again with version 0.0.5?

**Comment by ttamminen** [comment]
Everything okay now, thanks!
